version: '3.7'

services:
  mysql8:
    image: mysql:8
    platform: linux/x86_64
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/log:/var/log/mysql
    ports:
      - 3311:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Asia/Tokyo'
  mongodb:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    volumes:
      - ./docker/mongodb/db:/data/db
      - ./docker/mongodb/configdb:/data/configdb
    ports:
      - 27011:20717
